# Site settings
title: Talita Goulart
email: talita_goulart@yahoo.com.br
description: "Blog sobre desenvolvimento front-end"
baseurl: "/blog"
url: "http://www.talitagoulart.com.br"
twitter_username: talitacgo
github_username: talitagoulart
facebook_username: talita.c.goulart

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]